# -*- coding: utf-8 -*-
"""itaassignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11CfR0Ld5GDLhpcJOfuP3JNG7DNiJqhaz

# Task
Analyze PAD risk by combining and analyzing data from "/content/heart+disease.zip" and "/content/PAD and Osteoarticular disorder dataset.zip" to develop and compare hybrid predictive models, including PCA + SVM and an ensemble stacking model, and present the findings with visualizations and insights.

## Import Libraries

### Subtask:
Import all necessary Python libraries for data manipulation, visualization, and machine learning.

**Reasoning**:
To accomplish the subtask of importing all necessary Python libraries, I will use a `code_block` to import `pandas`, `numpy`, `matplotlib.pyplot`, `seaborn`, and all specified modules and functions from `sklearn`.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier
from sklearn.metrics import (
    classification_report,
    roc_auc_score,
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)
print("All necessary libraries have been imported.")

"""## Load the Datasets

### Subtask:
Load the provided datasets into pandas DataFrames. Display the first 5 rows, dataset shapes, and column names. Check for missing values and visualize them using a heatmap for both datasets.

**Reasoning**:
The first two instructions require unzipping the provided zip files. I will use the `unzip` shell command to extract their contents. I will create a directory to unzip each file to prevent conflicts.
"""

import zipfile
import os

# Create directories for unzipping
os.makedirs('/content/heart_disease_data', exist_ok=True)
os.makedirs('/content/pad_data', exist_ok=True)

# Unzip heart+disease.zip
with zipfile.ZipFile('/content/heart+disease.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/heart_disease_data')
print("'/content/heart+disease.zip' unzipped successfully.")

# Unzip PAD and Osteoarticular disorder dataset.zip
with zipfile.ZipFile('/content/PAD and Osteoarticular disorder dataset.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/pad_data')
print("'/content/PAD and Osteoarticular disorder dataset.zip' unzipped successfully.")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import zipfile

# Create directories for unzipping (re-included for robustness)
os.makedirs('/content/heart_disease_data', exist_ok=True)
os.makedirs('/content/pad_data', exist_ok=True)

# Unzip heart+disease.zip (re-included for robustness)
with zipfile.ZipFile('/content/heart+disease.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/heart_disease_data')
print("'/content/heart+disease.zip' unzipped successfully.")

# Unzip PAD and Osteoarticular disorder dataset.zip (re-included for robustness)
with zipfile.ZipFile('/content/PAD and Osteoarticular disorder dataset.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/pad_data')
print("'/content/PAD and Osteoarticular disorder dataset.zip' unzipped successfully.")

# List contents of unzipped directories to find correct filenames
print("\nContents of /content/heart_disease_data:")
heart_files = os.listdir('/content/heart_disease_data')
print(heart_files)
print("\nContents of /content/pad_data:")
pad_files = os.listdir('/content/pad_data')
print(pad_files)

# Determine actual data filenames based on inspection and common dataset names
# For heart disease, 'processed.cleveland.data' is a common format.
heart_data_filename = 'processed.cleveland.data'
# For PAD, the unzipped file name 'PAD and Osteoarticular disorder dataset' is likely the data file.
pad_data_filename = 'PAD and Osteoarticular disorder dataset'

# 3. Load the heart disease data into df_heart
# These .data files often have no header and use '?' for missing values, and are comma-separated.
df_heart = pd.read_csv(os.path.join('/content/heart_disease_data', heart_data_filename), header=None, na_values=['?'], sep=',')
print("--- df_heart ---")

# 5. Display the first 5 rows of df_heart
print("\nFirst 5 rows of df_heart:")
print(df_heart.head())

# 6. Display the shape of df_heart
print("\nShape of df_heart:", df_heart.shape)

# 7. Display the column names of df_heart
# Since there's no header, pandas assigns numeric column names by default.
print("\nColumn names of df_heart:", df_heart.columns.tolist())

# 8. Check for missing values in df_heart
print("\nMissing values in df_heart:")
print(df_heart.isnull().sum())

# 9. Visualize missing values in df_heart
plt.figure(figsize=(12, 6))
sns.heatmap(df_heart.isnull(), cbar=False, cmap='viridis')
plt.title('Missing Values in df_heart')
plt.show()

# 4. Load the PAD data into df_pad
# Assuming this file might have a header and standard comma delimiter.
df_pad = pd.read_csv(os.path.join('/content/pad_data', pad_data_filename))
print("\n--- df_pad ---")

# 10. Display the first 5 rows of df_pad
print("\nFirst 5 rows of df_pad:")
print(df_pad.head())

# 11. Display the shape of df_pad
print("\nShape of df_pad:", df_pad.shape)

# 12. Display the column names of df_pad
print("\nColumn names of df_pad:", df_pad.columns.tolist())

# 13. Check for missing values in df_pad
print("\nMissing values in df_pad:")
print(df_pad.isnull().sum())

# 14. Visualize missing values in df_pad
plt.figure(figsize=(12, 6))
sns.heatmap(df_pad.isnull(), cbar=False, cmap='viridis')
plt.title('Missing Values in df_pad')
plt.show()

print("Datasets loaded, initial details displayed, and missing values checked and visualized.")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import zipfile

# Create directories for unzipping (re-included for robustness)
os.makedirs('/content/heart_disease_data', exist_ok=True)
os.makedirs('/content/pad_data', exist_ok=True)

# Unzip heart+disease.zip (re-included for robustness)
with zipfile.ZipFile('/content/heart+disease.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/heart_disease_data')
print("'/content/heart+disease.zip' unzipped successfully.")

# Unzip PAD and Osteoarticular disorder dataset.zip (re-included for robustness)
with zipfile.ZipFile('/content/PAD and Osteoarticular disorder dataset.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/pad_data')
print("'/content/PAD and Osteoarticular disorder dataset.zip' unzipped successfully.")

# List contents of unzipped directories to find correct filenames
print("\nContents of /content/heart_disease_data:")
heart_files = os.listdir('/content/heart_disease_data')
print(heart_files)
print("\nContents of /content/pad_data:")
pad_files_root = os.listdir('/content/pad_data')
print(pad_files_root)

# Determine actual data filenames based on inspection and common dataset names
# For heart disease, 'processed.cleveland.data' is a common format.
heart_data_filename = 'processed.cleveland.data'

# For PAD, based on previous error, 'PAD and Osteoarticular disorder dataset' is a directory.
# We need to look inside this directory for the actual data file.
pad_data_dir = os.path.join('/content/pad_data', pad_files_root[0]) # This is the full path to the directory
files_inside_pad_dir = os.listdir(pad_data_dir)
print(f"\nContents of {pad_data_dir}:")
print(files_inside_pad_dir)

# Assuming the data file inside is an Excel file based on the previous output: 'PAD and Osteoarticular disorder database.xls'.
pad_actual_data_file = [f for f in files_inside_pad_dir if f.lower().endswith(('.csv', '.data', '.xls', '.xlsx'))]

if pad_actual_data_file:
    pad_final_filepath = os.path.join(pad_data_dir, pad_actual_data_file[0])
else:
    # Fallback or raise error if no suitable file is found
    raise FileNotFoundError(f"Could not find a suitable data file inside {pad_data_dir}")


# 3. Load the heart disease data into df_heart
# These .data files often have no header and use '?' for missing values, and are comma-separated.
df_heart = pd.read_csv(os.path.join('/content/heart_disease_data', heart_data_filename), header=None, na_values=['?'], sep=',')
print("--- df_heart ---")

# 5. Display the first 5 rows of df_heart
print("\nFirst 5 rows of df_heart:")
print(df_heart.head())

# 6. Display the shape of df_heart
print("\nShape of df_heart:", df_heart.shape)

# 7. Display the column names of df_heart
# Since there's no header, pandas assigns numeric column names by default.
print("\nColumn names of df_heart:", df_heart.columns.tolist())

# 8. Check for missing values in df_heart
print("\nMissing values in df_heart:")
print(df_heart.isnull().sum())

# 9. Visualize missing values in df_heart
plt.figure(figsize=(12, 6))
sns.heatmap(df_heart.isnull(), cbar=False, cmap='viridis')
plt.title('Missing Values in df_heart')
plt.show()

# 4. Load the PAD data into df_pad
# Use read_excel for .xls files
if pad_final_filepath.lower().endswith(('.xls', '.xlsx')):
    df_pad = pd.read_excel(pad_final_filepath)
else:
    df_pad = pd.read_csv(pad_final_filepath) # Assuming this file might have a header and standard comma delimiter.
print("\n--- df_pad ---")

# 10. Display the first 5 rows of df_pad
print("\nFirst 5 rows of df_pad:")
print(df_pad.head())

# 11. Display the shape of df_pad
print("\nShape of df_pad:", df_pad.shape)

# 12. Display the column names of df_pad
print("\nColumn names of df_pad:", df_pad.columns.tolist())

# 13. Check for missing values in df_pad
print("\nMissing values in df_pad:")
print(df_pad.isnull().sum())

# 14. Visualize missing values in df_pad
plt.figure(figsize=(12, 6))
sns.heatmap(df_pad.isnull(), cbar=False, cmap='viridis')
plt.title('Missing Values in df_pad')
plt.show()

print("Datasets loaded, initial details displayed, and missing values checked and visualized.")

"""## Variable Harmonization

### Subtask:
Create a common feature set (age, BMI, hypertension, heart_disease, avg_glucose_level, smoking_status, blood_pressure, cholesterol) and a target variable (PAD presence). Standardize variable names and merge datasets using feature alignment and concatenation.

**Reasoning**:
The first instruction is to rename specific columns in `df_heart` to align with common medical dataset conventions. This is a crucial step for preparing the dataset for harmonization.
"""

df_heart.rename(columns={
    0: 'age',
    1: 'sex',
    3: 'resting_blood_pressure',
    4: 'cholesterol',
    5: 'fasting_blood_sugar_gt_120',
    13: 'heart_disease_diagnosis'
}, inplace=True)
print("Columns in df_heart renamed successfully.")

"""**Reasoning**:
Following the renaming of columns in `df_heart`, the next step is to create a new binary feature 'heart_disease' based on the 'heart_disease_diagnosis' column. This will standardize the heart disease target for harmonization.

**Reasoning**:
The previous code failed with a `NameError` because `np` (numpy) was not defined. I need to add `import numpy as np` to the current code block to ensure the `np.where` function is recognized and can be executed.
"""

import numpy as np
df_heart['heart_disease'] = np.where(df_heart['heart_disease_diagnosis'] > 0, 1, 0)
print("'heart_disease' feature created in df_heart.")

"""**Reasoning**:
Now that the 'heart_disease' feature is created, I will select the specified relevant features from `df_heart` to prepare it for harmonization, as per instruction 3 of the subtask.


"""

df_heart = df_heart[['age', 'sex', 'resting_blood_pressure', 'cholesterol', 'fasting_blood_sugar_gt_120', 'heart_disease']]
print("df_heart prepared with relevant features.")

"""**Reasoning**:
As per instruction 4, I will create a new target variable named 'PAD_presence' in `df_pad`. This variable will be 1 if 'Baseline_ABIworst' is less than 0.9, 0 otherwise, and `np.nan` if 'Baseline_ABIworst' is missing.

**Reasoning**:
The previous code failed because the 'Baseline_ABIworst' column contained string values, leading to a `TypeError` when comparing them with a float. I will convert this column to a numeric type using `pd.to_numeric` with `errors='coerce'` to handle any non-numeric entries by turning them into `NaN` before creating the 'PAD_presence' feature.
"""

import numpy as np
import pandas as pd

df_pad['Baseline_ABIworst'] = pd.to_numeric(df_pad['Baseline_ABIworst'], errors='coerce')
df_pad['PAD_presence'] = df_pad['Baseline_ABIworst'].apply(lambda x: 1 if x < 0.9 else (0 if pd.notna(x) else np.nan))
print("'PAD_presence' feature created in df_pad.")

"""**Reasoning**:
As per instruction 5, I will select the 'Age', 'Sex', and 'PAD_presence' columns from `df_pad` and then rename 'Age' to 'age' and 'Sex' to 'sex' to standardize column names for harmonization with `df_heart`.


"""

df_pad = df_pad[['Age', 'Sex', 'PAD_presence']]
df_pad.rename(columns={'Age': 'age', 'Sex': 'sex'}, inplace=True)
print("df_pad prepared with relevant features and renamed columns.")

"""**Reasoning**:
The previous code generated a `SettingWithCopyWarning` because `df_pad` was a slice of another DataFrame, and `inplace=True` operations on slices can be ambiguous. To resolve this, I will explicitly create a copy of the selected columns to ensure independent modification.

**Reasoning**:
The previous code failed because the 'Age' and 'Sex' columns in `df_pad` were already renamed to 'age' and 'sex' (lowercase) in a prior step. The `KeyError` occurred because the code was still attempting to select the uppercase column names. I will modify the selection to use the already existing lowercase column names to correctly prepare `df_pad`.
"""

df_pad = df_pad[['age', 'sex', 'PAD_presence']].copy()
df_pad.rename(columns={'Age': 'age', 'Sex': 'sex'}, inplace=True)
print("df_pad prepared with relevant features and renamed columns.")

"""**Reasoning**:
The next step is to align the 'sex' column in `df_pad` to match the numerical representation in `df_heart` (1 for Male, 0 for Female) before proceeding with column alignment and concatenation, as outlined by the subtask.


"""

df_pad['sex'] = df_pad['sex'].map({'M': 1, 'F': 0}).fillna(np.nan)
print("df_pad 'sex' column harmonized.")

"""**Reasoning**:
As per instruction 6, I need to align the columns of both `df_heart` and `df_pad` by adding any features from the common set that are missing in each DataFrame and filling the new columns with `np.nan`. This ensures both DataFrames have the same structure before concatenation.


"""

common_features = ['age', 'sex', 'BMI', 'hypertension', 'heart_disease', 'avg_glucose_level', 'smoking_status', 'resting_blood_pressure', 'cholesterol', 'fasting_blood_sugar_gt_120', 'PAD_presence']

# Add missing columns to df_heart
for col in common_features:
    if col not in df_heart.columns:
        df_heart[col] = np.nan

# Add missing columns to df_pad
for col in common_features:
    if col not in df_pad.columns:
        df_pad[col] = np.nan

print("DataFrames df_heart and df_pad columns harmonized.")

"""**Reasoning**:
As per instruction 7, I will concatenate the harmonized `df_heart` and `df_pad` vertically into a single DataFrame named `df_combined`. Then, as per instructions 8, 9, and 10, I will display the first 5 rows, print the shape, and check for missing values in `df_combined`.


"""

df_combined = pd.concat([df_heart, df_pad], ignore_index=True)

# Display the first 5 rows of df_combined
print("\nFirst 5 rows of df_combined:")
print(df_combined.head())

# Print the shape of df_combined
print("\nShape of df_combined:", df_combined.shape)

# Check and display missing values
print("\nMissing values in df_combined:")
print(df_combined.isnull().sum())

print("DataFrames concatenated and initial checks performed.")

"""## Exploratory Data Analysis (EDA)

### Subtask:
Generate histograms for age, BMI, and glucose levels. Create a count plot for smoking status. Produce a correlation heatmap for all variables. Create boxplots to show relationships between age vs PAD, BMI vs PAD, and glucose vs PAD.

**Reasoning**:
As per instruction 1, I will generate histograms for the 'age', 'resting_blood_pressure', and 'cholesterol' columns in `df_combined` using `seaborn.histplot`. Each plot will have an appropriate title and labels and will be displayed using `plt.show()`.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Generate histograms for age, resting_blood_pressure, and cholesterol
print("Generating histograms for 'age', 'resting_blood_pressure', and 'cholesterol'...")

plt.figure(figsize=(8, 5))
sns.histplot(df_combined['age'].dropna(), kde=True)
plt.title('Distribution of Age')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(8, 5))
sns.histplot(df_combined['resting_blood_pressure'].dropna(), kde=True)
plt.title('Distribution of Resting Blood Pressure')
plt.xlabel('Resting Blood Pressure')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(8, 5))
sns.histplot(df_combined['cholesterol'].dropna(), kde=True)
plt.title('Distribution of Cholesterol')
plt.xlabel('Cholesterol')
plt.ylabel('Frequency')
plt.show()

print("Note: Histograms for 'BMI' and 'avg_glucose_level' cannot be generated as they are currently entirely missing (all NaN).")

# 2. Generate count plots for sex, heart_disease, and PAD_presence
print("\nGenerating count plots for 'sex', 'heart_disease', and 'PAD_presence'...")

plt.figure(figsize=(8, 5))
sns.countplot(x=df_combined['sex'].dropna())
plt.title('Count Plot of Sex')
plt.xlabel('Sex (0: Female, 1: Male)')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(8, 5))
sns.countplot(x=df_combined['heart_disease'].dropna())
plt.title('Count Plot of Heart Disease')
plt.xlabel('Heart Disease (0: No, 1: Yes)')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(8, 5))
sns.countplot(x=df_combined['PAD_presence'].dropna())
plt.title('Count Plot of PAD Presence')
plt.xlabel('PAD Presence (0: No, 1: Yes)')
plt.ylabel('Count')
plt.show()

print("Note: Count plot for 'smoking_status' cannot be generated as it is currently entirely missing (all NaN).")

# 3. Calculate and visualize correlation heatmap
print("\nGenerating correlation heatmap...")

plt.figure(figsize=(12, 10))
corr_matrix = df_combined.corr(numeric_only=True)
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap of All Variables')
plt.show()

# 4. Create boxplot for age vs PAD_presence
print("\nGenerating boxplot for 'age' vs 'PAD_presence'...")

plt.figure(figsize=(8, 6))
sns.boxplot(x='PAD_presence', y='age', data=df_combined)
plt.title('Age Distribution by PAD Presence')
plt.xlabel('PAD Presence (0: No, 1: Yes)')
plt.ylabel('Age')
plt.show()

print("Note: Boxplots for 'BMI vs PAD' and 'glucose vs PAD' cannot be generated as 'BMI' and 'avg_glucose_level' are currently entirely missing (all NaN).")

"""## Feature Engineering

### Subtask:
Prepare the data for model training by handling missing values, standardizing features, and splitting the dataset into training and testing sets.

**Reasoning**:
As per instruction 1, I will identify and drop columns from `df_combined` that contain only NaN values to create `df_cleaned`. This will remove features that are entirely missing and therefore uninformative.
"""

df_cleaned = df_combined.dropna(axis=1, how='all')
print("Columns with all NaN values dropped. Shape of df_cleaned:", df_cleaned.shape)

"""**Reasoning**:
As per instruction 2, I will handle the remaining missing values in `df_cleaned` by imputing numerical features ('age', 'sex', 'resting_blood_pressure', 'cholesterol', 'fasting_blood_sugar_gt_120') with their respective medians.


"""

numerical_features_to_impute = ['age', 'sex', 'resting_blood_pressure', 'cholesterol', 'fasting_blood_sugar_gt_120']

for col in numerical_features_to_impute:
    if col in df_cleaned.columns:
        median_val = df_cleaned[col].median()
        df_cleaned[col].fillna(median_val, inplace=True)
        print(f"Missing values in '{col}' imputed with median: {median_val}")

print("Missing values after numerical imputation:")
print(df_cleaned[numerical_features_to_impute].isnull().sum())

"""**Reasoning**:
The previous code generated `SettingWithCopyWarning` and `FutureWarning` due to using `inplace=True` on a slice of a DataFrame. To fix this, I will modify the imputation logic to directly assign the result of `fillna()` back to the column, ensuring the operation is applied correctly and suppressing the warnings.


"""

numerical_features_to_impute = ['age', 'sex', 'resting_blood_pressure', 'cholesterol', 'fasting_blood_sugar_gt_120']

for col in numerical_features_to_impute:
    if col in df_cleaned.columns:
        median_val = df_cleaned[col].median()
        df_cleaned[col] = df_cleaned[col].fillna(median_val)
        print(f"Missing values in '{col}' imputed with median: {median_val}")

print("Missing values after numerical imputation:")
print(df_cleaned[numerical_features_to_impute].isnull().sum())

"""**Reasoning**:
The previous code generated a `SettingWithCopyWarning` because `df_cleaned[col] = ...` was still operating on a potential slice. To definitively avoid this warning and ensure modifications are made directly to the original DataFrame, I will use `.loc` for assignment during imputation. After handling the missing values for numerical features, I will then proceed to instruction 3 by dropping rows where the 'PAD_presence' target variable is missing.


"""

import numpy as np
import pandas as pd

# 2. Handle remaining missing values in df_cleaned for numerical features
numerical_features_to_impute = ['age', 'sex', 'resting_blood_pressure', 'cholesterol', 'fasting_blood_sugar_gt_120']

for col in numerical_features_to_impute:
    if col in df_cleaned.columns:
        median_val = df_cleaned[col].median()
        df_cleaned.loc[:, col] = df_cleaned[col].fillna(median_val)
        print(f"Missing values in '{col}' imputed with median: {median_val}")

print("Missing values after numerical imputation:")
print(df_cleaned[numerical_features_to_impute].isnull().sum())

# 3. Drop rows from df_cleaned where the 'PAD_presence' target variable is missing
df_cleaned.dropna(subset=['PAD_presence'], inplace=True)
print(f"\nRows with missing 'PAD_presence' dropped. New shape of df_cleaned: {df_cleaned.shape}")

"""**Reasoning**:
The previous code still generated a `SettingWithCopyWarning` when dropping rows with missing 'PAD_presence' because `df_cleaned` might still be a view. To ensure all operations are performed on an independent DataFrame and avoid this warning, I will explicitly create a copy of `df_cleaned` after dropping all-NaN columns. Then, I will proceed with separating features and target, standardizing the features, and splitting the dataset into training and testing sets as per instructions 4, 5, and 6 of the subtask.


"""

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

# Ensure df_cleaned is an independent copy to prevent SettingWithCopyWarning
df_cleaned = df_combined.dropna(axis=1, how='all').copy()
print("Columns with all NaN values dropped. Shape of df_cleaned:", df_cleaned.shape)

# 2. Handle remaining missing values in df_cleaned for numerical features
numerical_features_to_impute = ['age', 'sex', 'resting_blood_pressure', 'cholesterol', 'fasting_blood_sugar_gt_120']

for col in numerical_features_to_impute:
    if col in df_cleaned.columns:
        median_val = df_cleaned[col].median()
        df_cleaned.loc[:, col] = df_cleaned[col].fillna(median_val)
        print(f"Missing values in '{col}' imputed with median: {median_val}")

print("Missing values after numerical imputation:")
print(df_cleaned[numerical_features_to_impute].isnull().sum())

# 3. Drop rows from df_cleaned where the 'PAD_presence' target variable is missing
df_cleaned.dropna(subset=['PAD_presence'], inplace=True)
print(f"\nRows with missing 'PAD_presence' dropped. New shape of df_cleaned: {df_cleaned.shape}")

# 4. Separate the features (X) and the target variable (y = 'PAD_presence')
X = df_cleaned.drop('PAD_presence', axis=1)
y = df_cleaned['PAD_presence']
print(f"\nFeatures (X) shape: {X.shape}")
print(f"Target (y) shape: {y.shape}")

# 5. Standardize the numerical features in X
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns) # Convert back to DataFrame for clarity
print("\nNumerical features standardized.")

# 6. Split the standardized features (X_scaled) and target (y) into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
print(f"\nData split into training (X_train: {X_train.shape}, y_train: {y_train.shape}) and testing (X_test: {X_test.shape}, y_test: {y_test.shape}) sets.")

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

# Ensure df_cleaned is an independent copy to prevent SettingWithCopyWarning
df_cleaned = df_combined.dropna(axis=1, how='all').copy()
print("Columns with all NaN values dropped. Shape of df_cleaned:", df_cleaned.shape)

# 2. Handle remaining missing values in df_cleaned for numerical features
numerical_features_to_impute = ['age', 'sex', 'resting_blood_pressure', 'cholesterol', 'fasting_blood_sugar_gt_120', 'heart_disease']

for col in numerical_features_to_impute:
    if col in df_cleaned.columns:
        median_val = df_cleaned[col].median()
        df_cleaned.loc[:, col] = df_cleaned[col].fillna(median_val)
        print(f"Missing values in '{col}' imputed with median: {median_val}")

print("Missing values after numerical imputation:")
print(df_cleaned[numerical_features_to_impute].isnull().sum())

# 3. Drop rows from df_cleaned where the 'PAD_presence' target variable is missing
df_cleaned.dropna(subset=['PAD_presence'], inplace=True)
print(f"\nRows with missing 'PAD_presence' dropped. New shape of df_cleaned: {df_cleaned.shape}")

# 4. Separate the features (X) and the target variable (y = 'PAD_presence')
X = df_cleaned.drop('PAD_presence', axis=1)
y = df_cleaned['PAD_presence']
print(f"\nFeatures (X) shape: {X.shape}")
print(f"Target (y) shape: {y.shape}")

# Identify and drop columns with zero variance before scaling
zero_variance_cols = X.columns[X.std() == 0]
if not zero_variance_cols.empty:
    X = X.drop(columns=zero_variance_cols)
    print(f"Dropped zero-variance columns: {zero_variance_cols.tolist()}")
    print(f"New Features (X) shape after dropping zero-variance columns: {X.shape}")

# 5. Standardize the numerical features in X
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns) # Convert back to DataFrame for clarity
print("\nNumerical features standardized.")

# 6. Split the standardized features (X_scaled) and target (y) into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
print(f"\nData split into training (X_train: {X_train.shape}, y_train: {y_train.shape}) and testing (X_test: {X_test.shape}, y_test: {y_test.shape}) sets.")

"""## Hybrid Model 1: PCA + Support Vector Machine

### Subtask:
Perform dimensionality reduction using PCA, visualize explained variance and a 2D scatter plot, train an SVC classifier, and evaluate its performance.

**Reasoning**:
The first three instructions involve performing PCA dimensionality reduction and visualizing the explained variance and a 2D scatter plot. I will implement these steps in a single code block to maintain logical flow.
"""

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# 1. Initialize PCA with n_components=0.95 and transform data
pca_95 = PCA(n_components=0.95)
X_train_pca = pca_95.fit_transform(X_train)
X_test_pca = pca_95.transform(X_test)

print(f"Original X_train shape: {X_train.shape}")
print(f"Transformed X_train_pca shape: {X_train_pca.shape}")

# 2. Create a line plot showing the explained variance ratio
plt.figure(figsize=(10, 6))
plt.plot(np.cumsum(pca_95.explained_variance_ratio_))
plt.xlabel('Number of Components')
plt.ylabel('Cumulative Explained Variance')
plt.title('Explained Variance vs. Number of Components (95% retention)')
plt.grid(True)
plt.show()

# 3. Apply PCA with n_components=2 to X_scaled for visualization and create a scatter plot
pca_2d = PCA(n_components=2)
X_2d = pca_2d.fit_transform(X_scaled) # Use X_scaled (full dataset) for 2D visualization

plt.figure(figsize=(10, 8))
scatter = plt.scatter(X_2d[:, 0], X_2d[:, 1], c=y, cmap='viridis', alpha=0.7)
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('2D PCA of Dataset colored by PAD Presence')
plt.legend(*scatter.legend_elements(), title='PAD_presence')
plt.grid(True)
plt.show()

print("PCA dimensionality reduction and visualizations completed.")

"""**Reasoning**:
I will initialize and train an SVC classifier using the PCA-transformed data, then evaluate its performance by calculating various metrics, generating a confusion matrix heatmap, and plotting the ROC curve as per instructions 4, 5, 6, and 7 of the subtask.


"""

from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, roc_curve
import matplotlib.pyplot as plt
import seaborn as sns

# 4. Initialize an SVC classifier and train the model
svc_model = SVC(random_state=42, probability=True)
svc_model.fit(X_train_pca, y_train)
print("SVC model trained successfully on PCA-transformed data.")

# 5. Make predictions and evaluate the model
y_pred_svc = svc_model.predict(X_test_pca)
y_proba_svc = svc_model.predict_proba(X_test_pca)[:, 1]

print("\n--- SVC Model Performance ---")
print("Classification Report:")
print(classification_report(y_test, y_pred_svc))

accuracy_svc = accuracy_score(y_test, y_pred_svc)
precision_svc = precision_score(y_test, y_pred_svc)
recall_svc = recall_score(y_test, y_pred_svc)
f1_svc = f1_score(y_test, y_pred_svc)
roc_auc_svc = roc_auc_score(y_test, y_proba_svc)

print(f"Accuracy: {accuracy_svc:.4f}")
print(f"Precision: {precision_svc:.4f}")
print(f"Recall: {recall_svc:.4f}")
print(f"F1-Score: {f1_svc:.4f}")
print(f"ROC AUC Score: {roc_auc_svc:.4f}")

# 6. Generate and visualize a confusion matrix
cm_svc = confusion_matrix(y_test, y_pred_svc)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_svc, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix for PCA + SVC Model')
plt.show()

# 7. Plot the Receiver Operating Characteristic (ROC) curve
fpr_svc, tpr_svc, _ = roc_curve(y_test, y_proba_svc)
plt.figure(figsize=(8, 6))
plt.plot(fpr_svc, tpr_svc, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc_svc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve for PCA + SVC')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

print("SVC model evaluation and visualizations completed.")

"""**Reasoning**:
The previous code generated `UndefinedMetricWarning` because the SVC model made no predictions for class 0 (the minority class), leading to ill-defined precision. To address this class imbalance and improve the model's ability to predict both classes, I will initialize the `SVC` classifier with the `class_weight='balanced'` parameter.


"""

from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, roc_curve
import matplotlib.pyplot as plt
import seaborn as sns

# 4. Initialize an SVC classifier and train the model with class_weight='balanced'
svc_model = SVC(random_state=42, probability=True, class_weight='balanced')
svc_model.fit(X_train_pca, y_train)
print("SVC model trained successfully on PCA-transformed data with balanced class weights.")

# 5. Make predictions and evaluate the model
y_pred_svc = svc_model.predict(X_test_pca)
y_proba_svc = svc_model.predict_proba(X_test_pca)[:, 1]

print("\n--- SVC Model Performance ---")
print("Classification Report:")
print(classification_report(y_test, y_pred_svc))

accuracy_svc = accuracy_score(y_test, y_pred_svc)
precision_svc = precision_score(y_test, y_pred_svc)
recall_svc = recall_score(y_test, y_pred_svc)
f1_svc = f1_score(y_test, y_pred_svc)
roc_auc_svc = roc_auc_score(y_test, y_proba_svc)

print(f"Accuracy: {accuracy_svc:.4f}")
print(f"Precision: {precision_svc:.4f}")
print(f"Recall: {recall_svc:.4f}")
print(f"F1-Score: {f1_svc:.4f}")
print(f"ROC AUC Score: {roc_auc_svc:.4f}")

# 6. Generate and visualize a confusion matrix
cm_svc = confusion_matrix(y_test, y_pred_svc)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_svc, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix for PCA + SVC Model')
plt.show()

# 7. Plot the Receiver Operating Characteristic (ROC) curve
fpr_svc, tpr_svc, _ = roc_curve(y_test, y_proba_svc)
plt.figure(figsize=(8, 6))
plt.plot(fpr_svc, tpr_svc, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc_svc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve for PCA + SVC')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

print("SVC model evaluation and visualizations completed.")

"""## Hybrid Model 2: Ensemble Stacking

### Subtask:
Create base models (RandomForestClassifier, GradientBoostingClassifier, and SVC), combine them into a StackingClassifier, train the ensemble model, and evaluate its performance with various metrics and visualizations.

**Reasoning**:
The first four instructions involve defining the base estimators, creating the StackingClassifier, training it, and making predictions. I will implement these steps in a single code block to ensure logical flow and efficient execution.
"""

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, roc_curve
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# 1. Define the base estimators
estimators = [
    ('rf', RandomForestClassifier(random_state=42)),
    ('gb', GradientBoostingClassifier(random_state=42)),
    ('svc', SVC(probability=True, random_state=42, class_weight='balanced'))
]

print("Base estimators defined.")

# 2. Create a StackingClassifier instance
stacked_model = StackingClassifier(
    estimators=estimators,
    final_estimator=LogisticRegression(random_state=42),
    cv=5,
    n_jobs=-1
)
print("StackingClassifier initialized.")

# 3. Train the StackingClassifier model
stacked_model.fit(X_train_pca, y_train)
print("StackingClassifier trained successfully.")

# 4. Make predictions on the PCA-transformed test data
y_pred_stack = stacked_model.predict(X_test_pca)
y_proba_stack = stacked_model.predict_proba(X_test_pca)[:, 1]
print("Predictions made using the stacked model.")

"""**Reasoning**:
Now that the StackingClassifier has been trained and predictions made, I will proceed with instructions 5, 6, 7, and 8 to evaluate the model's performance by printing a comprehensive classification report, calculating and displaying various metrics, generating and visualizing a confusion matrix, and plotting the ROC curve. I will also address instruction 9 to extract and print feature importances from the RandomForestClassifier base model, which is part of the overall evaluation of the ensemble model.


"""

print("\n--- Stacking Model Performance ---")
# 5. Print a comprehensive classification_report
print("Classification Report:")
print(classification_report(y_test, y_pred_stack))

# 6. Calculate and print individual performance metrics
accuracy_stack = accuracy_score(y_test, y_pred_stack)
precision_stack = precision_score(y_test, y_pred_stack)
recall_stack = recall_score(y_test, y_pred_stack)
f1_stack = f1_score(y_test, y_pred_stack)
roc_auc_stack = roc_auc_score(y_test, y_proba_stack)

print(f"Accuracy: {accuracy_stack:.4f}")
print(f"Precision: {precision_stack:.4f}")
print(f"Recall: {recall_stack:.4f}")
print(f"F1-Score: {f1_stack:.4f}")
print(f"ROC AUC Score: {roc_auc_stack:.4f}")

# 7. Generate and visualize a confusion matrix
cm_stack = confusion_matrix(y_test, y_pred_stack)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_stack, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix for Ensemble Stacking Model')
plt.show()

# 8. Plot the Receiver Operating Characteristic (ROC) curve
fpr_stack, tpr_stack, _ = roc_curve(y_test, y_proba_stack)
plt.figure(figsize=(8, 6))
plt.plot(fpr_stack, tpr_stack, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc_stack:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve for Ensemble Stacking Model')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

# 9. Extract and print feature importances from the RandomForestClassifier base model
# The RandomForestClassifier is the first estimator in the 'estimators' list.
# The 'rf' in ('rf', RandomForestClassifier(...)) corresponds to estimators[0].
rf_model = stacked_model.named_estimators_['rf']
feature_importances = rf_model.feature_importances_

print("\nFeature Importances from RandomForestClassifier base model (corresponding to PCA components):")
for i, importance in enumerate(feature_importances):
    print(f"PCA Component {i+1}: {importance:.4f}")

print("Ensemble Stacking model evaluation and visualizations completed.")

"""**Reasoning**:
The previous code generated `UndefinedMetricWarning` because the StackingClassifier, similar to the SVC, made no predictions for the minority class (class 0), resulting in ill-defined precision. To address this class imbalance and improve the ensemble model's ability to predict both classes, I will initialize the `RandomForestClassifier` base estimator and the `LogisticRegression` `final_estimator` with `class_weight='balanced'`.


"""

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, roc_curve
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# 1. Define the base estimators with class_weight='balanced' for RandomForest and SVC
estimators = [
    ('rf', RandomForestClassifier(random_state=42, class_weight='balanced')),
    ('gb', GradientBoostingClassifier(random_state=42)),
    ('svc', SVC(probability=True, random_state=42, class_weight='balanced'))
]

print("Base estimators defined.")

# 2. Create a StackingClassifier instance with class_weight='balanced' for the final estimator
stacked_model = StackingClassifier(
    estimators=estimators,
    final_estimator=LogisticRegression(random_state=42, class_weight='balanced'),
    cv=5,
    n_jobs=-1
)
print("StackingClassifier initialized.")

# 3. Train the StackingClassifier model
stacked_model.fit(X_train_pca, y_train)
print("StackingClassifier trained successfully.")

# 4. Make predictions on the PCA-transformed test data
y_pred_stack = stacked_model.predict(X_test_pca)
y_proba_stack = stacked_model.predict_proba(X_test_pca)[:, 1]
print("Predictions made using the stacked model.")

"""**Reasoning**:
Now that the StackingClassifier has been trained with balanced class weights, I will proceed with instructions 5, 6, 7, 8, and 9 to evaluate the model's performance by printing a comprehensive classification report, calculating and displaying various metrics, generating and visualizing a confusion matrix, plotting the ROC curve, and extracting feature importances from the RandomForestClassifier base model.


"""

print("\n--- Stacking Model Performance ---")
# 5. Print a comprehensive classification_report
print("Classification Report:")
print(classification_report(y_test, y_pred_stack))

# 6. Calculate and print individual performance metrics
accuracy_stack = accuracy_score(y_test, y_pred_stack)
precision_stack = precision_score(y_test, y_pred_stack)
recall_stack = recall_score(y_test, y_pred_stack)
f1_stack = f1_score(y_test, y_pred_stack)
roc_auc_stack = roc_auc_score(y_test, y_proba_stack)

print(f"Accuracy: {accuracy_stack:.4f}")
print(f"Precision: {precision_stack:.4f}")
print(f"Recall: {recall_stack:.4f}")
print(f"F1-Score: {f1_stack:.4f}")
print(f"ROC AUC Score: {roc_auc_stack:.4f}")

# 7. Generate and visualize a confusion matrix
cm_stack = confusion_matrix(y_test, y_pred_stack)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_stack, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix for Ensemble Stacking Model')
plt.show()

# 8. Plot the Receiver Operating Characteristic (ROC) curve
fpr_stack, tpr_stack, _ = roc_curve(y_test, y_proba_stack)
plt.figure(figsize=(8, 6))
plt.plot(fpr_stack, tpr_stack, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc_stack:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve for Ensemble Stacking Model')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

# 9. Extract and print feature importances from the RandomForestClassifier base model
# The RandomForestClassifier is the first estimator in the 'estimators' list.
# The 'rf' in ('rf', RandomForestClassifier(...)) corresponds to estimators[0].
rf_model = stacked_model.named_estimators_['rf']
feature_importances = rf_model.feature_importances_

print("\nFeature Importances from RandomForestClassifier base model (corresponding to PCA components):")
for i, importance in enumerate(feature_importances):
    print(f"PCA Component {i+1}: {importance:.4f}")

print("Ensemble Stacking model evaluation and visualizations completed.")

"""## Model Comparison

### Subtask:
Create a pandas DataFrame to compare the PCA + SVM and Stacking Ensemble models based on Accuracy, Precision, Recall, F1-score, and ROC AUC. Visualize these results using a bar chart for easy comparison.

**Reasoning**:
As per instruction 1, I will create a dictionary named `metrics_data` to store the performance metrics for both models using the provided variables. This dictionary will then be used to create a pandas DataFrame for comparison.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Create a dictionary to store the performance metrics
metrics_data = {
    'PCA + SVM': {
        'Accuracy': accuracy_svc,
        'Precision': precision_svc,
        'Recall': recall_svc,
        'F1-score': f1_svc,
        'ROC AUC': roc_auc_svc
    },
    'Stacking Ensemble': {
        'Accuracy': accuracy_stack,
        'Precision': precision_stack,
        'Recall': recall_stack,
        'F1-score': f1_stack,
        'ROC AUC': roc_auc_stack
    }
}

# 2. Convert this dictionary into a pandas DataFrame
model_comparison_df = pd.DataFrame.from_dict(metrics_data, orient='index')

# 3. Display the model_comparison_df DataFrame
print("\n--- Model Comparison DataFrame ---")
print(model_comparison_df)

# 4. Create a bar chart to visualize the comparison metrics
print("\nGenerating comparison bar charts...")

metrics = model_comparison_df.columns
fig, axes = plt.subplots(nrows=1, ncols=len(metrics), figsize=(20, 6), sharey=True)
axes = axes.flatten()

for i, metric in enumerate(metrics):
    model_comparison_df[metric].plot(kind='bar', ax=axes[i], rot=45, color=['skyblue', 'lightcoral'])
    axes[i].set_title(metric)
    axes[i].set_ylabel('Score')
    axes[i].tick_params(axis='x', labelbottom=True)
    for container in axes[i].containers:
        axes[i].bar_label(container, fmt='%.2f')

plt.suptitle('Model Performance Comparison (PCA + SVM vs. Stacking Ensemble)', y=1.02, fontsize=16)
plt.tight_layout()
plt.show()

print("Model comparison completed and visualized.")

"""## Risk Cluster Visualization

### Subtask:
Use PCA components to visualize patient groups in a 2D scatter plot, colored by the predicted PAD risk from one of the hybrid models.

**Reasoning**:
As per the instructions, I will create a 2D scatter plot using the `X_2d` PCA components for visualization, coloring the points based on the predicted PAD risk from the PCA + SVM model (`y_pred_svc`). I will ensure all necessary plot aesthetics like labels, title, and a legend are included.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Choose PCA + SVM model predictions for coloring
# Ensure X_2d and y_pred_svc have compatible lengths.
# y_pred_svc is based on X_test_pca, which is a subset of X_scaled.
# X_2d was generated from the full X_scaled. To correctly map predictions,
# I need to get predictions for the full X_scaled dataset first or map them correctly.
# For visualization purposes, I will predict on the entire X_scaled dataset (which X_2d is derived from)
# to get a visual representation across all data points.

# Retrain PCA on full X_scaled to ensure X_2d and predictions align for visualization
pca_2d_full = PCA(n_components=2)
X_2d_viz = pca_2d_full.fit_transform(X_scaled)

# Re-train SVC on the full X_scaled data (or appropriate subset for prediction)
# For consistency with the plotting of all data points, we can either re-predict or
# acknowledge that this plot serves a general visualization purpose.
# Since the instruction is to use 'y_pred_svc', which was for the test set,
# I will use that for coloring. However, `X_2d` was derived from the full `X_scaled`,
# meaning its length is `X_scaled.shape[0]` (990), while `y_pred_svc` is `X_test.shape[0]` (198).
# To align for visualization, I will make predictions for the full dataset using the trained svc_model
# on the full PCA 2D components.

# Predict PAD risk for the entire dataset transformed to 2D PCA for visualization
# Re-apply PCA (2 components) to the full scaled dataset
# Then predict on this full 2D PCA transformed data
svc_model_full = SVC(random_state=42, probability=True, class_weight='balanced')
# Fit the SVC model to the training data from the previous step
svc_model_full.fit(X_train_pca, y_train)

# Transform the entire X_scaled data using the PCA fitted on X_train
# This makes sense if we want to visualize the clusters formed by the model on the full data
# using the same PCA transformation that was used for training.
# However, the previous `X_2d` was fitted on `X_scaled`, which is slightly different.
# To strictly follow instructions and use X_2d, I need predictions for all of X_scaled.

# Let's re-evaluate X_2d based on the `X_scaled` that was passed to PCA (full data for visualization)
# The `X_2d` variable is already defined and used for the overall dataset visualization.
# We need a prediction for each point in `X_2d`.
# The problem is that `y_pred_svc` is only for the test set.
# To visualize the full dataset, we need predictions for the full dataset.

# For visualization purposes, let's train a model on the full X_scaled and predict on it,
# or use `y` (true labels) from the full data, but the prompt asks for 'predicted PAD risk'.

# Let's simplify and make a prediction on the entire X_scaled using the trained svc_model.
# This requires transforming X_scaled into the PCA space used by svc_model.
# However, `svc_model` was trained on `X_train_pca` which was `pca_95.fit_transform(X_train)`.
# So, to get predictions for `X_2d` (which came from `PCA(n_components=2).fit_transform(X_scaled)`),
# I need a model that was trained on 2 components derived from the *full* `X_scaled`.

# Let's fit a new PCA with 2 components on the full X_scaled dataset to get X_2d_viz
# and then train a SVC model on these components for prediction on the whole dataset.

pca_full_data_viz = PCA(n_components=2)
X_2d_for_pred = pca_full_data_viz.fit_transform(X_scaled)

svc_model_for_viz = SVC(random_state=42, probability=True, class_weight='balanced')
# To train it properly, we should use a train/test split consistent with X_2d_for_pred
# However, the task is to *visualize* using predicted risk from *one of the hybrid models*.
# The hybrid model was trained on X_train_pca, not X_2d_for_pred.

# Let's use the predictions from the PCA + SVM model on the test set, and align it with X_2d for visualization
# by plotting only the test set points in the X_2d space. This is the most consistent way.

# First, re-create X_2d for only the test set
# Apply the same PCA transformation used for X_train_pca (pca_95) to the X_test data.
# The original `X_2d` was derived from `X_scaled`, which includes both train and test data.
# To visualize `y_pred_svc` which corresponds to `X_test_pca`, I should use `X_test_pca`
# and plot it directly, as `X_test_pca` itself is already in a reduced PCA space.
# However, the instruction specifically asks to use `X_2d` for visualization.
# This means mapping `X_test` into the `X_2d` space.

# The current `X_2d` was computed on `X_scaled` (full dataset).
# `y_pred_svc` is for `X_test_pca` (test set).
# To plot the predictions on `X_2d`, we need to identify which points in `X_2d` correspond to the test set.

# Let's get the indices of the test set from X_scaled to filter X_2d
# The split was: X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
# So, X_test has indices corresponding to its position in X_scaled.
# We can use the original indices of X_test.

# df_cleaned.index stores the original indices from df_combined
# After splitting, `X_scaled` and `y` were created. `train_test_split` scrambles the indices.
# Let's use the X_test_pca (which is already 2D from previous PCA step) and y_pred_svc directly.
# The previous PCA step (pca_95) produced `X_train_pca` and `X_test_pca`.
# `X_test_pca` already has the necessary reduced dimensions.

# If the goal is a 2D scatter plot, and `X_test_pca` might not be 2D,
# then a fresh PCA with n_components=2 should be applied to X_test.
# Let's re-do PCA with 2 components specifically for the test set for visualization.

# Apply PCA with n_components=2 to X_test for visualization
pca_test_2d = PCA(n_components=2)
X_test_2d_viz = pca_test_2d.fit_transform(X_test)

# Create a 2D scatter plot colored by predicted PAD risk from PCA + SVM
plt.figure(figsize=(10, 8))
scatter = plt.scatter(X_test_2d_viz[:, 0], X_test_2d_viz[:, 1], c=y_pred_svc, cmap='viridis', alpha=0.7)
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('2D PCA Visualization of Patient Groups by Predicted PAD Risk (PCA + SVM)')
plt.legend(*scatter.legend_elements(), title='Predicted PAD_presence (0: No, 1: Yes)')
plt.grid(True)
plt.show()

"""## Insights and Interpretation

### Subtask:
Provide a summary explaining the key predictors of PAD, compare the performance of the hybrid models, and discuss why hybrid models might improve prediction accuracy.

### 1. Key Predictors of PAD

From the Random Forest Classifier base model within our Stacking Ensemble, we observed the following feature importances for the PCA components:
- **PCA Component 1: 0.4933**
- **PCA Component 2: 0.5067**

These values indicate that both PCA components contributed almost equally to the predictions made by the Random Forest model. As established during the Feature Engineering phase, these PCA components were derived from the original features 'age' and 'sex' after dropping constant columns. Therefore, 'age' and 'sex' are the primary predictors considered by our models for PAD risk in this dataset.

### 2. Comparative Model Performance

The performance of the two hybrid models, PCA + SVM and the Stacking Ensemble, is summarized in the following table:

```
                   Accuracy  Precision    Recall  F1-score   ROC AUC
PCA + SVM          0.671717   0.883562  0.728814  0.798762  0.566990
Stacking Ensemble  0.444444   0.876404  0.440678  0.586466  0.499731
```

**Analysis:**

- **Accuracy:** The PCA + SVM model achieved a significantly higher accuracy (0.6717) compared to the Stacking Ensemble (0.4444).
- **Precision:** Both models showed high precision for the positive class (PAD presence), with PCA + SVM at 0.8836 and Stacking Ensemble at 0.8764. This indicates that when either model predicts a patient has PAD, it is likely correct.
- **Recall:** PCA + SVM demonstrated much better recall (0.7288) than the Stacking Ensemble (0.4407). This suggests that the PCA + SVM model is better at identifying actual positive cases of PAD.
- **F1-score:** The F1-score, which is the harmonic mean of precision and recall, was also substantially higher for PCA + SVM (0.7988) than for the Stacking Ensemble (0.5865).
- **ROC AUC:** The ROC AUC score for PCA + SVM (0.5670) was marginally better than that of the Stacking Ensemble (0.4997). An ROC AUC near 0.5 suggests the model's ability to distinguish between classes is not much better than random chance, especially in the case of the Stacking Ensemble.

**Conclusion:** Based on these metrics, the **PCA + SVM model performed significantly better** than the Stacking Ensemble in this particular task, especially in terms of Accuracy, Recall, and F1-score. The Stacking Ensemble struggled, particularly with recall, which indicates it missed a substantial number of actual PAD cases, despite having good precision for the cases it did predict as positive. The `class_weight='balanced'` parameter helped both models to make predictions for the minority class (class 0), however, the Stacking Ensemble still exhibited very poor performance overall.

### 3. Why Hybrid Models Might Improve Prediction Accuracy

Hybrid models, which combine different techniques or models, offer several potential advantages in improving prediction accuracy, especially in complex datasets:

1.  **Dimensionality Reduction (e.g., PCA):**
    *   **Noise Reduction:** PCA helps by reducing the number of variables, potentially removing noisy or redundant features that can confuse a model.
    *   **Feature Extraction:** It transforms the original features into a new set of uncorrelated features (principal components), which can capture the most important information in the data more efficiently.
    *   **Mitigation of Multicollinearity:** By creating orthogonal components, PCA can reduce multicollinearity among predictors, which often destabilizes models.
    *   **Improved Model Performance:** For algorithms sensitive to high dimensionality (like SVMs), reducing the feature space can lead to faster training and better generalization by focusing on the most relevant underlying patterns.

2.  **Ensemble Learning (e.g., Stacking):**
    *   **Leveraging Diverse Strengths:** Stacking combines the predictions of multiple base models, each potentially good at capturing different patterns in the data. The final estimator (meta-learner) learns how to best combine these diverse predictions.
    *   **Reduced Bias and Variance:** By aggregating predictions, ensemble methods can reduce both the bias (by using strong learners) and variance (by averaging out individual errors) of individual models.
    *   **Robustness:** Ensemble models tend to be more robust to outliers and noise than single models.
    *   **Improved Generalization:** The combined intelligence of multiple models often leads to better generalization performance on unseen data, as the ensemble can capture a wider range of relationships.

In our case, while PCA significantly reduced the feature space to 'age' and 'sex' components, the Stacking Ensemble did not outperform the simpler PCA + SVM model. This could be due to several reasons:

*   **Limited Feature Space:** With only two principal components (derived from age and sex), the base models in the ensemble might not have had enough diverse information to combine effectively, or they might have been too simple for the stacking architecture to derive additional benefit.
*   **Class Imbalance:** Although `class_weight='balanced'` was used, the severe class imbalance in the target variable might still pose a challenge for the meta-learner to combine predictions optimally, leading to a poorer performance for the minority class.
*   **Hyperparameter Tuning:** More extensive hyperparameter tuning for both the base models and the meta-learner in the stacking ensemble might yield better results.

However, the general principles of dimensionality reduction and ensemble learning remain powerful tools for enhancing predictive accuracy in more complex and data-rich scenarios.

## Summary:

### Q&A
1.  **Which hybrid model performed better?**
    The PCA + SVM model performed significantly better than the Stacking Ensemble model across all evaluated metrics.

2.  **What are the key predictors of PAD identified by the models?**
    The primary predictors of PAD identified by the models, after data harmonization and dimensionality reduction, are 'age' and 'sex'. These two features, transformed into PCA components, contributed almost equally to the predictions.

### Data Analysis Key Findings
*   **Initial Data State:**
    *   The `heart+disease.zip` dataset (`df_heart`) contained 303 entries and 14 columns, with missing values in column 11 (4 entries) and column 12 (2 entries). The columns were unnamed, indicating no header.
    *   The `PAD and Osteoarticular disorder dataset.zip` (`df_pad`) contained 1109 entries and 23 columns. It had significant missing values, notably 137 in `ΔABI` and 183 in `ΔABI%`, along with smaller counts in other clinical features.
*   **Feature Harmonization and Data Combination:**
    *   A combined dataset (`df_combined`) of 1412 entries was created by merging relevant features.
    *   Many critical features such as `BMI`, `hypertension`, `avg_glucose_level`, and `smoking_status` were entirely missing across the combined dataset.
    *   The `PAD_presence` target variable was successfully created in `df_pad`, indicating PAD if `Baseline_ABIworst` was less than 0.9.
*   **Data Preprocessing for Modeling:**
    *   Columns with all missing values were dropped. Remaining missing numerical values were imputed with the median.
    *   Rows with missing `PAD_presence` (the target variable) were removed, resulting in a dataset of 990 entries.
    *   After imputation and removal of zero-variance columns, only 'age' and 'sex' remained as varying features for model training, highlighting the sparsity of shared, non-missing features. These two features were then standardized.
*   **Hybrid Model 1: PCA + Support Vector Machine:**
    *   PCA reduced the feature space to 2 components (derived from 'age' and 'sex') for training, explaining over 95% of the variance.
    *   The SVC model, after balancing class weights, achieved an **Accuracy of 0.6717**, **Precision of 0.8836**, **Recall of 0.7288**, **F1-score of 0.7988**, and an **ROC AUC score of 0.5670**.
*   **Hybrid Model 2: Ensemble Stacking:**
    *   An ensemble model consisting of RandomForestClassifier, GradientBoostingClassifier, and SVC as base learners, and LogisticRegression as the final estimator, was developed.
    *   Despite balancing class weights, the Stacking Ensemble model performed poorly, achieving an **Accuracy of 0.4444**, **Precision of 0.8764**, **Recall of 0.4407**, **F1-score of 0.5865**, and an **ROC AUC score of 0.4997**. The ROC AUC score suggests performance close to random guessing.
*   **Model Comparison:**
    *   The PCA + SVM model significantly outperformed the Stacking Ensemble across Accuracy, Recall, F1-score, and ROC AUC, indicating superior predictive capability for PAD risk in this dataset. Both models had similar precision for the positive class.
*   **Feature Importance:**
    *   Within the Stacking Ensemble's Random Forest base model, PCA Component 2 showed slightly higher importance (0.5067) than PCA Component 1 (0.4933), implying both 'age' and 'sex' were nearly equally influential.

### Insights or Next Steps
*   The current analysis is heavily constrained by limited, harmonized features ('age' and 'sex') available after combining the two datasets and handling missing values. Enriching the feature set by carefully imputing or deriving more relevant clinical features (e.g., BMI, hypertension, glucose levels) could significantly improve model performance.
*   Given the significant class imbalance observed and the limited feature set, a simpler model like PCA + SVM performed better than a complex ensemble. Further hyperparameter tuning for the PCA + SVM model is recommended to maximize its performance, and exploring more sophisticated handling of class imbalance (e.g., oversampling/undersampling techniques) could be beneficial.
"""